// Command face_search demonstrates biometric face search via the Relata Go SDK.
//
// Scenario: A law-enforcement analyst has a CCTV still of a suspect and wants
// to identify the individual by matching against the engine's FaceEncoding
// index. The workflow:
//  1. Run MATCH_FACE against a stored image reference.
//  2. Resolve each candidate hit through the IdentityIndex.
//  3. Fetch associated travel records for the top match.
//  4. Show the raw SQL generated by the builder (for logging / audit trail).
//
// IMPORTANT: MATCH_FACE is gated by the Cedar ACL policy. The caller must hold
// the BIOMETRIC_SEARCH permission on the relevant compartment; queries without
// it are rejected with ErrForbidden.
//
// Usage:
//
//	go run ./examples/face_search \
//	    -url   http://localhost:8080  \
//	    -token $RELATA_BEARER_TOKEN   \
//	    -image s3://relata-evidence/cctv-frame-2024-11-03T14:22:00Z.jpg \
//	    -top   10
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"time"

	"github.com/OpenWorkBench-Co/RelataDB/sdks/go/relata"
)

func main() {
	url := flag.String("url", "http://localhost:8080", "Relata server base URL")
	token := flag.String("token", "", "Bearer token")
	imageRef := flag.String("image",
		"s3://relata-evidence/cctv-frame-2024-11-03T14:22:00Z.jpg",
		"Image reference (object-store key or base64 fragment)")
	topK := flag.Int("top", 10, "Maximum candidate matches")
	minScore := flag.Float64("min-score", 0.85, "Minimum similarity score (0.0–1.0)")
	asOf := flag.String("as-of", "2025-01-01", "Bi-temporal snapshot date")
	flag.Parse()

	client := relata.New(*url, &relata.ClientOptions{
		BearerToken:    *token,
		DefaultPurpose: "investigation",
		Timeout:        90 * time.Second, // face search can be slow on large indexes
	})

	ctx := context.Background()

	// ── Step 1: Build and inspect the SQL before executing ───────────────────
	// Calling .SQL() on a builder lets you log or audit the generated query
	// without actually executing it. Useful for pre-execution review.
	builder := relata.MatchFace(*imageRef, *topK).
		Purpose("investigation").
		Where(fmt.Sprintf("similarity_score >= %g", *minScore)).
		AsOf(*asOf).
		WithProvenance()

	generatedSQL := builder.SQL()
	fmt.Printf("=== Generated SQL ===\n%s\n\n", generatedSQL)

	// ── Step 2: Execute face search ───────────────────────────────────────────
	fmt.Printf("=== MATCH_FACE: top %d candidates (min_score=%.2f) ===\n",
		*topK, *minScore)

	result, err := builder.Execute(ctx, client)
	if err != nil {
		if errors.Is(err, relata.ErrForbidden) {
			log.Fatal("access denied: caller lacks BIOMETRIC_SEARCH permission")
		}
		if errors.Is(err, relata.ErrUnauthorized) {
			log.Fatal("bearer token missing or invalid")
		}
		log.Fatalf("face search failed: %v", err)
	}

	fmt.Printf("Candidates: %d  elapsed: %d ms  query_id: %s\n\n",
		result.RowCount, result.ElapsedMs, result.QueryID)

	if result.RowCount == 0 {
		fmt.Println("No matches above threshold. Investigation closed (no candidates).")
		return
	}

	// Print the candidate list with confidence scores.
	result.Each(func(row map[string]any) {
		fmt.Printf("  entity_id=%-36v  score=%-6v  name=%v\n",
			row["entity_id"], row["similarity_score"], row["display_name"])
	})

	// ── Step 3: Resolve top match through IdentityIndex ───────────────────────
	topMatch := result.Rows[0]
	entityID, _ := topMatch["entity_id"].(string)
	score, _ := topMatch["similarity_score"].(float64)

	fmt.Printf("\n=== Step 3: Resolve top match (entity_id=%s, score=%.3f) ===\n",
		entityID, score)

	idResult, err := relata.LookupIdentity(entityID).
		Purpose("investigation").
		WithProvenance().
		Execute(ctx, client)
	if err != nil {
		log.Fatalf("identity resolution failed: %v", err)
	}

	idResult.Each(func(row map[string]any) {
		fmt.Printf("  id_type=%-20v  value=%v  _source=%v\n",
			row["id_type"], row["value"], row["_source"])
	})

	// ── Step 4: Travel records for the top match ──────────────────────────────
	fmt.Printf("\n=== Step 4: Travel records for entity %s ===\n", entityID)

	travelResult, err := relata.NewQuery("SELECT * FROM TravelEvent").
		Purpose("investigation").
		Where(fmt.Sprintf("entity_id = '%s'", entityID)).
		Where("event_type IN ('departure', 'arrival', 'visa_check')").
		AsOf(*asOf).
		Limit(50).
		Execute(ctx, client)
	if err != nil {
		log.Fatalf("travel query failed: %v", err)
	}

	fmt.Printf("Travel events: %d in %d ms\n", travelResult.RowCount, travelResult.ElapsedMs)
	travelResult.Each(func(row map[string]any) {
		fmt.Printf("  event_type=%-15v  timestamp=%v  location=%v\n",
			row["event_type"], row["event_timestamp"], row["location_name"])
	})

	// ── Step 5: Output summary ────────────────────────────────────────────────
	fmt.Printf("\n=== Face search summary ===\n")
	fmt.Printf("Image        : %s\n", *imageRef)
	fmt.Printf("Candidates   : %d\n", result.RowCount)
	fmt.Printf("Top match    : entity_id=%s  score=%.3f\n", entityID, score)
	fmt.Printf("Travel events: %d\n", travelResult.RowCount)
}
