package relata

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// newTestClient builds a Client pointed at srv with the given options merged.
func newTestClient(srv *httptest.Server, opts *ClientOptions) *Client {
	if opts == nil {
		opts = &ClientOptions{}
	}
	if opts.Timeout == 0 {
		opts.Timeout = 2 * time.Second
	}
	return New(srv.URL, opts)
}

func TestQuery_HappyPath(t *testing.T) {
	var gotPath, gotMethod, gotPurpose string
	var gotBody map[string]any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotMethod = r.Method
		b, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(b, &gotBody)
		gotPurpose = r.Header.Get("X-Request-ID")
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprint(w, `{"query_id":"q-1","elapsed_ms":7,"row_count":2,"columns":["id","name"],"rows":[{"id":1,"name":"A"},{"id":2,"name":"B"}]}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{DefaultPurpose: "analytics"})
	result, err := c.Query(context.Background(), "SELECT * FROM Person LIMIT 2")
	if err != nil {
		t.Fatalf("Query: %v", err)
	}
	if gotMethod != "POST" || gotPath != "/query" {
		t.Fatalf("method/path = %s %s", gotMethod, gotPath)
	}
	if gotBody["purpose"] != "analytics" || gotBody["sql"] != "SELECT * FROM Person LIMIT 2" {
		t.Fatalf("payload = %v", gotBody)
	}
	if gotPurpose == "" {
		t.Fatal("X-Request-ID not set on request")
	}
	if result.QueryID != "q-1" || result.RowCount != 2 || len(result.Rows) != 2 {
		t.Fatalf("result = %+v", result)
	}
	if result.Rows[0]["name"] != "A" {
		t.Fatalf("row0 = %v", result.Rows[0])
	}
}

func TestQuery_WireShapeNormalisation_DataArray(t *testing.T) {
	// Server emits rows-as-int-count + sibling "data" array (the legacy wire shape).
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprint(w, `{"query_id":"q-2","elapsed_ms":3,"rows":2,"data":[{"id":1},{"id":2}],"columns":["id"]}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{DefaultPurpose: "analytics"})
	result, err := c.Query(context.Background(), "SELECT id FROM T")
	if err != nil {
		t.Fatalf("Query: %v", err)
	}
	if len(result.Rows) != 2 {
		t.Fatalf("expected 2 rows from data array, got %d", len(result.Rows))
	}
	if result.RowCount != 2 {
		t.Fatalf("RowCount = %d, want 2", result.RowCount)
	}
	if len(result.Columns) != 1 || result.Columns[0] != "id" {
		t.Fatalf("Columns = %v", result.Columns)
	}
}

func TestQuery_WireShapeNormalisation_RowsAsIntOnly(t *testing.T) {
	// rows is an int and no data array → empty Rows, RowCount tracks the count.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprint(w, `{"query_id":"q-3","rows":0}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{DefaultPurpose: "analytics"})
	result, err := c.Query(context.Background(), "SELECT id FROM T")
	if err != nil {
		t.Fatalf("Query: %v", err)
	}
	if len(result.Rows) != 0 {
		t.Fatalf("expected 0 rows, got %d", len(result.Rows))
	}
	if result.RowCount != 0 {
		t.Fatalf("RowCount = %d, want 0", result.RowCount)
	}
}

func TestQuery_PurposeRequired(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		t.Fatal("server should not be called when purpose is missing")
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	_, err := c.Query(context.Background(), "SELECT 1")
	if !errors.Is(err, ErrPurposeRequired) {
		t.Fatalf("err = %v, want ErrPurposeRequired", err)
	}
}

func TestQuery_PurposeOverride(t *testing.T) {
	var gotPurpose any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		b, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(b, &gotPurpose)
		fmt.Fprint(w, `{"rows":[]}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{DefaultPurpose: "analytics"})
	if _, err := c.Query(context.Background(), "SELECT 1", WithPurpose("audit")); err != nil {
		t.Fatal(err)
	}
	m, ok := gotPurpose.(map[string]any)
	if !ok {
		t.Fatalf("payload not an object: %T", gotPurpose)
	}
	if m["purpose"] != "audit" {
		t.Fatalf("purpose = %v, want audit", m["purpose"])
	}
}

func TestRequestIDHeaderAutoGenerated(t *testing.T) {
	var seen []string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seen = append(seen, r.Header.Get("X-Request-ID"))
		fmt.Fprint(w, `{"status":"ok","profile":"free","node_id":"n1"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	for i := 0; i < 3; i++ {
		if _, err := c.Health(context.Background()); err != nil {
			t.Fatal(err)
		}
	}
	if len(seen) != 3 {
		t.Fatalf("seen = %v", seen)
	}
	for _, id := range seen {
		if id == "" {
			t.Fatalf("empty request id in %v", seen)
		}
	}
	if seen[0] == seen[1] || seen[1] == seen[2] {
		t.Fatalf("request ids should be unique per request, got %v", seen)
	}
}

func TestRequestIDCallerPinned(t *testing.T) {
	var seen string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seen = r.Header.Get("X-Request-ID")
		fmt.Fprint(w, `{"status":"ok","profile":"free","node_id":"n1"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{Headers: map[string]string{"X-Request-ID": "trace-abc"}})
	if _, err := c.Health(context.Background()); err != nil {
		t.Fatal(err)
	}
	if seen != "trace-abc" {
		t.Fatalf("X-Request-ID = %q, want trace-abc (caller-pinned wins)", seen)
	}
}

func TestTenantAndDelegationHeaders(t *testing.T) {
	var gotTenant, gotActing, gotDelegated string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotTenant = r.Header.Get("X-Relata-Tenant-Id")
		gotActing = r.Header.Get("X-Acting-As")
		gotDelegated = r.Header.Get("X-Delegated-By")
		fmt.Fprint(w, `{"status":"ok","profile":"free","node_id":"n1"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{
		Tenant:      "org-acme",
		ActingAs:    "user-bob",
		DelegatedBy: "user-alice",
	})
	if _, err := c.Health(context.Background()); err != nil {
		t.Fatal(err)
	}
	if gotTenant != "org-acme" || gotActing != "user-bob" || gotDelegated != "user-alice" {
		t.Fatalf("tenant/acting/delegated = %q/%q/%q", gotTenant, gotActing, gotDelegated)
	}
}

func TestRetryOn503(t *testing.T) {
	var attempts int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		n := atomic.AddInt32(&attempts, 1)
		if n < 3 {
			w.WriteHeader(http.StatusServiceUnavailable)
			return
		}
		fmt.Fprint(w, `{"status":"ok","profile":"free","node_id":"n1"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{MaxRetries: 3, RetryBackoff: time.Millisecond})
	_, err := c.Health(context.Background())
	if err != nil {
		t.Fatalf("expected success after retry, got %v", err)
	}
	if attempts < 3 {
		t.Fatalf("attempts = %d, want >= 3", attempts)
	}
}

func TestRetryExhaustedReturnsServerError(t *testing.T) {
	var attempts int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&attempts, 1)
		w.WriteHeader(http.StatusBadGateway)
	}))
	defer srv.Close()

	c := newTestClient(srv, &ClientOptions{MaxRetries: 2, RetryBackoff: time.Millisecond})
	_, err := c.Health(context.Background())
	if err == nil {
		t.Fatal("expected error after retries exhausted")
	}
	if !errors.Is(err, ErrServerError) {
		t.Fatalf("err = %v, want ErrServerError", err)
	}
	var re *RelataError
	if !errors.As(err, &re) {
		t.Fatalf("expected *RelataError, got %T", err)
	}
	if re.StatusCode != 502 {
		t.Fatalf("StatusCode = %d, want 502", re.StatusCode)
	}
}

func TestRFC7807ErrorFields(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/problem+json")
		w.Header().Set("X-Request-ID", "rid-xyz")
		w.WriteHeader(http.StatusForbidden)
		fmt.Fprint(w, `{"type":"https://relata.io/errors/forbidden","title":"Forbidden","detail":"policy deny","code":"RELATA.ACL.DENY","retryable":false,"request_id":"rid-xyz"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	_, err := c.Health(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
	var re *RelataError
	if !errors.As(err, &re) {
		t.Fatalf("expected *RelataError, got %T", err)
	}
	if re.StatusCode != 403 {
		t.Fatalf("StatusCode = %d", re.StatusCode)
	}
	if !errors.Is(err, ErrForbidden) {
		t.Fatalf("err should wrap ErrForbidden, got %v", err)
	}
	if re.Code != "RELATA.ACL.DENY" {
		t.Fatalf("Code = %q", re.Code)
	}
	if re.TypeURL != "https://relata.io/errors/forbidden" {
		t.Fatalf("TypeURL = %q", re.TypeURL)
	}
	if re.RequestID != "rid-xyz" {
		t.Fatalf("RequestID = %q", re.RequestID)
	}
	if re.Message != "policy deny" {
		t.Fatalf("Message = %q", re.Message)
	}
}

func TestRateLimitedErrorRetryAfter(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Retry-After", "5")
		w.WriteHeader(http.StatusTooManyRequests)
		fmt.Fprint(w, `{"detail":"slow down"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	_, err := c.Health(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
	var re *RelataError
	if !errors.As(err, &re) {
		t.Fatalf("expected *RelataError, got %T", err)
	}
	if !errors.Is(err, ErrRateLimited) {
		t.Fatalf("err should wrap ErrRateLimited, got %v", err)
	}
	if !errors.Is(err, ErrQuotaExhausted) {
		t.Fatalf("ErrQuotaExhausted alias should still match, got %v", err)
	}
	if re.RetryAfter != 5*time.Second {
		t.Fatalf("RetryAfter = %v, want 5s", re.RetryAfter)
	}
}

func TestSentinelMapping(t *testing.T) {
	cases := []struct {
		status int
		sent   error
	}{
		{401, ErrUnauthorized},
		{403, ErrForbidden},
		{404, ErrNotFound},
		{409, ErrConflict},
		{422, ErrValidation},
		{500, ErrServerError},
	}
	for _, tc := range cases {
		t.Run(fmt.Sprintf("%d", tc.status), func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(tc.status)
			}))
			defer srv.Close()
			c := newTestClient(srv, nil)
			_, err := c.Health(context.Background())
			if err == nil {
				t.Fatal("expected error")
			}
			if !errors.Is(err, tc.sent) {
				t.Fatalf("status %d: err = %v, want %v", tc.status, err, tc.sent)
			}
		})
	}
}

func TestStats(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/debug/stats" {
			t.Fatalf("path = %s", r.URL.Path)
		}
		fmt.Fprint(w, `{"records":10,"states":200,"snapshot_rows":50,"log_leaves":7,"tokens":3,"extra":"x"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	stats, err := c.Stats(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if stats.Records != 10 || stats.States != 200 || stats.SnapshotRows != 50 || stats.LogLeaves != 7 || stats.Tokens != 3 {
		t.Fatalf("stats = %+v", stats)
	}
	if stats.Raw["extra"] != "x" {
		t.Fatalf("Raw did not capture extra field: %v", stats.Raw)
	}
}

func TestVersion(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/version" {
			t.Fatalf("path = %s", r.URL.Path)
		}
		fmt.Fprint(w, `{"version":"1.2.3","commit":"abc","profile":"server","schema_version":"v3","features":["a","b"]}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	v, err := c.Version(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if v.Version != "1.2.3" || v.Commit != "abc" || v.Profile != "server" || v.SchemaVersion != "v3" || len(v.Features) != 2 {
		t.Fatalf("version = %+v", v)
	}
}

func TestReady(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/health/ready" {
			t.Fatalf("path = %s", r.URL.Path)
		}
		fmt.Fprint(w, `{"status":"ok"}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	rep, err := c.Ready(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if !rep.IsReady || rep.Status != "ok" {
		t.Fatalf("ready = %+v", rep)
	}
}

func TestIngestDocument(t *testing.T) {
	var gotBody map[string]any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/ingest/document" {
			t.Fatalf("path = %s", r.URL.Path)
		}
		b, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(b, &gotBody)
		fmt.Fprint(w, `{"report_id":"r-1","chunks_ingested":3,"warnings":[],"schema_version":"1.0","queue_depth":2}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	resp, err := c.IngestDocument(context.Background(), `{"c":1}`, `{"m":1}`)
	if err != nil {
		t.Fatal(err)
	}
	if resp.ReportID != "r-1" || resp.ChunksIngested != 3 || resp.SchemaVersion != "1.0" || resp.QueueDepth != 2 {
		t.Fatalf("resp = %+v", resp)
	}
	if gotBody["chunks_jsonl"] != `{"c":1}` || gotBody["manifest_json"] != `{"m":1}` {
		t.Fatalf("payload = %v", gotBody)
	}
}

func TestAuditCountChainCorrupted(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `{"entries":5,"chain_valid":false}`)
	}))
	defer srv.Close()

	c := newTestClient(srv, nil)
	resp, err := c.AuditCount(context.Background())
	if !errors.Is(err, ErrChainCorrupted) {
		t.Fatalf("err = %v, want ErrChainCorrupted", err)
	}
	if resp == nil || resp.Entries != 5 || resp.ChainValid {
		t.Fatalf("resp = %+v", resp)
	}
}

func TestConnectionError(t *testing.T) {
	// Point at a closed port to force a connection error.
	c := New("http://127.0.0.1:1", &ClientOptions{Timeout: 200 * time.Millisecond})
	_, err := c.Health(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
	if !errors.Is(err, ErrConnection) {
		t.Fatalf("err = %v, want ErrConnection", err)
	}
}

func TestColumnHelper(t *testing.T) {
	r := &QueryResult{Rows: []map[string]any{
		{"id": float64(1), "name": "A"},
		{"id": float64(2)},
	}}
	col := r.Column("name")
	if len(col) != 2 || col[0] != "A" || col[1] != nil {
		t.Fatalf("Column = %v", col)
	}
}

func TestParseRetryAfter(t *testing.T) {
	if d := parseRetryAfter("5"); d != 5*time.Second {
		t.Fatalf("delta-seconds parse = %v", d)
	}
	if d := parseRetryAfter(""); d != 0 {
		t.Fatalf("empty = %v", d)
	}
	if d := parseRetryAfter("garbage"); d != 0 {
		t.Fatalf("garbage = %v", d)
	}
}

func TestEachHelper(t *testing.T) {
	r := &QueryResult{Rows: []map[string]any{{"a": 1}, {"a": 2}}}
	var sum int
	r.Each(func(row map[string]any) {
		sum += row["a"].(int)
	})
	if sum != 3 {
		t.Fatalf("sum = %d", sum)
	}
}

func TestNewRequestID(t *testing.T) {
	id, err := newRequestID()
	if err != nil {
		t.Fatal(err)
	}
	if len(id) != 36 {
		t.Fatalf("id len = %d, want 36 (uuid v4)", len(id))
	}
	if strings.Count(id, "-") != 4 {
		t.Fatalf("id = %q, not uuid-shaped", id)
	}
	// v4 marker at position 14.
	if id[14] != '4' {
		t.Fatalf("id = %q, not v4", id)
	}
	// variant 10xx at position 19.
	switch id[19] {
	case '8', '9', 'a', 'b':
	default:
		t.Fatalf("id = %q, variant byte = %q", id, string(id[19]))
	}
}

func TestSearch_HappyPath(t *testing.T) {
	// #670 — verify Search() maps the wire shape to SearchResponse.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/search" {
			t.Errorf("unexpected path %q", r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{
			"hits": [{"id":"p1","object_type":"Person","fields":{"name":"Alice"},"score":1.23,"highlights":{"name":"<em>Alice</em>"}}],
			"total": 1,
			"facets": {"tenant_id": {"EUROPOL": 1}},
			"processing_time_ms": 5
		}`))
	}))
	defer srv.Close()

	client := newTestClient(srv, nil)
	resp, err := client.Search(t.Context(), "alice", "Person", WithSearchLimit(10), WithHighlight())
	if err != nil {
		t.Fatalf("Search returned error: %v", err)
	}
	if resp.Total != 1 {
		t.Errorf("Total = %d, want 1", resp.Total)
	}
	if len(resp.Hits) != 1 {
		t.Fatalf("Hits length = %d, want 1", len(resp.Hits))
	}
	if resp.Hits[0].ID != "p1" {
		t.Errorf("Hit ID = %q, want p1", resp.Hits[0].ID)
	}
	if resp.ProcessingTimeMs != 5 {
		t.Errorf("ProcessingTimeMs = %d, want 5", resp.ProcessingTimeMs)
	}
}

func TestQuery_ProcessingTimeMs(t *testing.T) {
	// #1252: verify ProcessingTimeMs is populated from processing_time_ms when
	// present, and falls back to elapsed_ms for backward compat.
	t.Run("from_processing_time_ms", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprint(w, `{"query_id":"q-2","elapsed_ms":3,"processing_time_ms":7,"row_count":0,"rows":[]}`)
		}))
		defer srv.Close()
		c := newTestClient(srv, &ClientOptions{DefaultPurpose: "analytics"})
		result, err := c.Query(context.Background(), "SELECT 1")
		if err != nil {
			t.Fatal(err)
		}
		if result.ProcessingTimeMs != 7 {
			t.Errorf("ProcessingTimeMs = %d, want 7", result.ProcessingTimeMs)
		}
	})

	t.Run("fallback_to_elapsed_ms", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprint(w, `{"query_id":"q-3","elapsed_ms":5,"row_count":0,"rows":[]}`)
		}))
		defer srv.Close()
		c := newTestClient(srv, &ClientOptions{DefaultPurpose: "analytics"})
		result, err := c.Query(context.Background(), "SELECT 1")
		if err != nil {
			t.Fatal(err)
		}
		if result.ProcessingTimeMs != 5 {
			t.Errorf("ProcessingTimeMs = %d (fallback from elapsed_ms), want 5", result.ProcessingTimeMs)
		}
	})
}
